# Port to listen on
port: 8008

# Root URL for returned shortlinks
# Be sure to omit protocol and trailing slash
domain: localhost:8008

# Require users to login before creating shortlinks
requireLogin: true

# Lifetime of a session token in seconds (Default 24h)
sessionLifetime: 86400

analytics:
  # Use this to quickly disable all analytics
  enabled: true
  # Collect IP address on all requests
  ip: true
  # Collect User Agent on all requests
  useragent: true
  # Collect Referer URL on all requests
  referer: true
  ### Cloudflare
  # Make sure to Add visitor location headers, via:
  # https://dash.cloudflare.com/[accountID]/[domain]/rules/transform-rules/managed-transforms
  cf_ipcountry: true
  cf_ipcity: true
  ###